Repository AY1920S1-CS2103T-W13-3/main, pull requests merged in 2019-10, with the labels that each got.

#76 Updated glossary in DeveloperGuide.adoc
  docs/ContactUs.adoc
  docs/DeveloperGuide.adoc
Labels: type.Task

#142 Added JsonAdaptedCheatSheet.java and JsonAdaptedContent.java
  src/main/java/seedu/address/model/cheatsheet/CheatSheet.java
  src/main/java/seedu/address/storage/JsonAdaptedCheatSheet.java
  src/main/java/seedu/address/storage/JsonAdaptedContent.java
  src/main/main.iml
Labels: priority.High, type.Task

#199 Updated UG
  docs/UserGuide.adoc
Labels: priority.High

#246 Update UG for deletion prompt and cheatsheet increment
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/cheatsheet/AddCheatSheetCommand.java
  src/main/java/seedu/address/model/cheatsheet/Content.java
Labels: priority.Medium
